import pandas as pd

import matplotlib.pyplot as plt
import seaborn as sns
df = pd.read_csv('big_mart_sales.csv')
print(df.head())
print(df.columns)
#print(df.tail())
#print(df['Item_Type'])
#print(df['Item_MRP'])
#print(df['Item_Outlet_Sales'])
#print(df['Outlet_Size'])
#print(df.isnull().sum())
#df['Item_Weight']=df['Item_Weight'].fillna(df['Item_Weight'].mean())
#df['Outlet_Size']= df['Outlet_Size'].fillna(df['Item_Weight'].mean())
#df['Item_Weight']=df['Item_Weight'].fillna(method='ffill')
#df['Outlet_Size']= df['Outlet_Size'].fillna(method='ffill')
#df['Item_Weight']=df['Item_Weight'].fillna('unknown')
#df['Outlet_Size']= df['Outlet_Size'].fillna('unknown')
#print(df.isnull().sum())
#sales_by_location = df.groupby('Outlet_Location_Type')['Item_Outlet_Sales'].sum()
#print(sales_by_location)
# avg_sales_by_product_type = df.groupby('Item_Type')['Item_Outlet_Sales'].mean()
# print(avg_sales_by_product_type)
# sorted_by_items = df.sort_values(by=['Item_Type', 'Item_Outlet_Sales'], ascending=False)
# print(sorted_by_items)
#sorted_desc = df.sort_values(by=['Item_Outlet_Sales'])
#print(sorted_desc)

#sns.lineplot(df['Item_Outlet_Sales'],  color='red')
#sns.barplot(df['Item_Type'], color='blue')
fat_content = df['Item_Fat_Content'].value_counts()
plt.pie(fat_content)
plt.title('Fat Content Distribution')
plt.show()