import seaborn as sns
import matplotlib.pyplot as plt
df = sns.load_dataset('titanic')
print(df.head())
print(df.columns)
#sns.set_style('whitegrid')
#plt.title("My plot")
#plt.xlabel("X axis")
#plt.ylabel("Y axis")
#plt.show()
#sns.countplot(data=df, x='sex' ,hue='survived', palette='pastel')
#plt.title("sex distribution")
#plt.legend(title='survived',labels=['No','yes'])
#sns.boxplot(data=df, x='class',y='age', palette='Set3')
#plt.title("Age distribution across passenger classes")
#plt.xlabel("Passenger class")
#plt.ylabel("Age")
numeric_value=df.select_dtypes(include='number')
print(numeric_value.head())
corr_matrix= numeric_value.corr()
print(corr_matrix)
plt.figure(figsize=(10,8))
sns.heatmap(corr_matrix, annot=True, cmap='coolwarm',linewidths=0.5)
plt.title("Correlation Matrix")
plt.show()
